### ISSUE TITLE
Selection actions in context menu

### ISSUE THREAD

**Issue by SilvanVerhoeven** [hpi-swa-teaching/ChangesBrowser#83]
As a developer, I want to have several commands available to change the selection of the history list via a context menu that opens on right-click, because I want to facilitate different selection scenarios that would be tedious to accomplish otherwise.

**Acceptance criteria:**
* [ ] A context menu opens on a right-click on the history list (the one on the left).
* [ ] The context menu has the option "Ignore all", which deselects all changes in all methods.
* [ ] The context menu has the option "All latest changes", which selects the latest change of each method.
* [ ] The context menu has the option "Ignore all except this one", deselects all changes of all methods except the current method.

**Comment by marcelgarus** [comment]
The original issue was:

As a developer, I want to invert the current selection of the change list via a context menu that open on right click, because I don't want too many different buttons but one fitting list of actions for the context I am working in.

**Acceptance criteria:**
* [ ] A context menu opens on a right click on the change list.
* [ ] The context menu has the option "Invert selection".
* [ ] The selection of the change list is inverted after clicking on "Invert selection".
